# Generated by Django 5.1.6 on 2025-02-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("country", models.CharField(max_length=2)),
                ("date", models.DateField()),
                ("type", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("cached_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["country", "year"],
                        name="holidays_ho_country_64fc6b_idx",
                    ),
                    models.Index(fields=["name"], name="holidays_ho_name_4fed38_idx"),
                ],
            },
        ),
    ]
